2025-08-20 12:31:19,962 ERROR: Exception on /reset_password_request [POST] [in C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_mail\__init__.py", line 540, in send
    message.send(connection)
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_mail\__init__.py", line 482, in send
    connection.send(self)
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_mail\__init__.py", line 177, in send
    self.host.sendmail(
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 861, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 611, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
                   ^^^^^^^^^^^
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 451, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\Desktop\MicroBlog\app\routes.py", line 176, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\HP3\Desktop\MicroBlog\app\email.py", line 14, in send_password_reset_email
    send_email('[MicroBlog] reset your password',
  File "C:\Users\HP3\Desktop\MicroBlog\app\email.py", line 9, in send_email
    mail.send(msg)
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_mail\__init__.py", line 539, in send
    with self.connect() as connection:
  File "C:\Users\HP3\Desktop\MicroBlog\venv\Lib\site-packages\flask_mail\__init__.py", line 136, in __exit__
    self.host.quit()
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 993, in quit
    res = self.docmd("quit")
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 431, in docmd
    self.putcmd(cmd, args)
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 378, in putcmd
    self.send(f'{s}{CRLF}')
  File "C:\Users\HP3\AppData\Local\Programs\Python\Python312\Lib\smtplib.py", line 365, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
